name: medical_records_frontend
description: "A Flutter Web frontend for the Medical Records system."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0" # Updated to support Flutter 3.5.4 and above

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  json_annotation: ^4.8.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true
